name: python_foundation
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37hc8dfbb8_1001
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - boost-cpp=1.72.0=hdf9ef73_0
  - brotlipy=0.7.0=py37h9bfed18_1000
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hec6a9b0_1003
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37h356ff06_0
  - cfitsio=3.470=hddc9c06_5
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cryptography=2.9.2=py37he655712_0
  - curl=7.69.1=h2d98d24_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=h4a8c4bd_2
  - fiona=1.8.13=py37h9c7205d_1
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.10.2=h8da9a1a_0
  - freexl=1.0.5=h1de35cc_1002
  - gdal=3.0.4=py37h08e9697_10
  - geographiclib=1.50=py_0
  - geopandas=0.7.0=py_1
  - geopy=1.22.0=pyh9f0ad1d_0
  - geos=3.8.1=h4a8c4bd_0
  - geotiff=1.6.0=hd8796ba_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.2.1=h0b31af3_2
  - glib=2.64.2=h577aef8_1
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.6=nompi_h3e39495_100
  - icu=64.2=h6de7cb9_1
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py37hc8dfbb8_0
  - importlib_metadata=1.6.0=0
  - ipykernel=5.2.1=py37h43977f1_0
  - ipython=7.14.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9c=h1de35cc_1001
  - json-c=0.13.1=h575e443_1002
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab=2.1.2=py_0
  - jupyterlab_server=1.1.3=py_0
  - kealib=1.4.13=h40102fb_1
  - krb5=1.17.1=hddcf347_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=hc0b9707_0
  - libcxx=10.0.0=1
  - libdap4=3.20.6=h8c15375_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h4a8c4bd_1007
  - libgdal=3.0.4=h242383b_10
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - libkml=1.3.0=h169b8f9_1011
  - liblapack=3.8.0=16_openblas
  - libnetcdf=4.7.4=nompi_ha11d67f_104
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libpq=12.2=h489d428_1
  - libsodium=1.0.17=h01d97ff_0
  - libspatialindex=1.9.3=h4a8c4bd_3
  - libspatialite=4.3.0a=h658e6c1_1038
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - libxml2=2.9.10=h53d96d6_0
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h4a8c4bd_1
  - markupsafe=1.1.1=py37h9bfed18_1
  - mistune=0.8.4=py37h9bfed18_1001
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_1
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy=1.18.4=py37h7687784_0
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1g=h0b31af3_0
  - packaging=20.1=py_0
  - pandas=1.0.3=py37h94625e5_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py37_3
  - pixman=0.38.0=h01d97ff_1003
  - poppler=0.87.0=h3232a60_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=h62ab893_1
  - proj=7.0.0=hbce2d5c_4
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py37hbd4ead9_0
  - pyrsistent=0.16.0=py37h9bfed18_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.1=py37haec44b1_0
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=pyh8c360ce_2
  - rtree=0.9.4=py37h8526d28_1
  - send2trash=1.5.0=py_0
  - setuptools=46.0.0=py37_0
  - shapely=1.7.0=py37hfcf0db4_3
  - six=1.14.0=py_1
  - sqlite=3.31.1=h5c1f38d_1
  - tbb=2018.0.5=h04f5b5a_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.7=h84aa2a7_1
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h9bfed18_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - tzcode=2020a=h0b31af3_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py37_0
  - xerces-c=3.2.2=h8f8adb3_1004
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h4b3e974_3
  - pip:
    - python-dotenv==0.13.0
prefix: /Users/ujaval/opt/anaconda3/envs/python_foundation

